# Generated by Django 5.0.6 on 2024-05-16 02:50

from django.db import migrations


def insert_months(apps, schema_editor):
    Month = apps.get_model('habits', 'Month')
    months = ['January', 'February', 'March', 'April', 'May', 'June',
              'July', 'August', 'September', 'October', 'November', 'December']
    for month in months:
        Month.objects.create(name=month)


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_months),
    ]
